# Generated by Django 5.1.1 on 2024-09-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ("title",)},
        ),
    ]
